backend:
  name: git-gateway
  local_backend: true
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  # - name: "blog"
  #   label: "Blog"
  #   folder: "src/pages/blog"
  #   create: true
  #   slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  #   fields:
  #     - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
  #     - {label: "Title", name: "title", widget: "string"}
  #     - {label: "Publish Date", name: "date", widget: "datetime"}
  #     - {label: "Description", name: "description", widget: "text"}
  #     - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
  #     - {label: "Featured Image", name: "featuredimage", widget: image}
  #     - {label: "Body", name: "body", widget: "markdown"}
  #     - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - label: EasySection
            name: easy
            widget: object
            fields: [
              {label: TitleTop, name: title_top, widget: string},
              {label: TitleBottom, name: title_bottom, widget: string},
              {label: Subtitle, name: subtitle, widget: text}
            ]
          - label: AboutSection
            name: about
            widget: object
            fields: [
              {label: Image, name: image, widget: image},
              {label: Title, name: title, widget: string},
              {label: Text, name: text, widget: text},
            ]
          - label: FreeSection
            name: free
            widget: list
            fields:
              - {label: Image, name: image, widget: image}
              - {label: Title, name: title, widget: string}
              - {label: Subtitle, name: subtitle, widget: string}
              - {label: Text, name: text, widget: text}
          - label: HowSection
            name: how
            widget: object
            fields: [
              {label: Title, name: title, widget: string},
              {label: Order Steps, name: order_steps, widget: list, fields: [
                {label: Title, name: title, widget: string},
                {label: Text, name: text, widget: text}
              ]},
              {label: Buy Steps, name: buy_steps, widget: list, fields: [
                {label: Title, name: title, widget: string},
                {label: Text, name: text, widget: text}
              ]}
            ]
          - label: OkaySection
            name: okay
            widget: object
            fields: [
              {label: Image, name: image, widget: image},
              {label: Title, name: title, widget: string},
              {label: OkayList, name: list, widget: list, fields: [{label: Text, name: text, widget: text}]}
            ]
          - label: CheapestSection
            name: cheapest
            widget: object
            fields: [
              {label: Title, name: title, widget: string},
              {label: Products, name: products, widget: list, fields: [
                {label: Name, name: name, widget: string},
                {label: Image, name: image, widget: image},
                {label: CompareList, name: compare, widget: list, fields: [
                  {label: Logo, name: logo, widget: image},
                  {label: Title, name: title, widget: string},
                  {label: Duration, name: duration, widget: string},
                  {label: Price, name: price, widget: string}
                ]}
              ]}
            ]
          - {label: ShopsSection, name: shops, widget: object, fields: [
              {label: ShopsTitle, name: title, widget: string},
              {label: ShopsSubtitle, name: subtitle, widget: text},
              {label: ShopsList, name: list, widget: list, fields: [{label: Shop, name: shop, widget: image}]}
            ]}
          - {label: FeedbackSection, name: feedbacks, widget: object, fields: [
              {label: FeedbackTitle, name: title, widget: string},
              {label: FeedbackList, name: list, widget: list, fields: [{label: Feedback, name: feedback, widget: image}]}
            ]}
          - label: LandingImages
            name: landing_images
            widget: object
            fields: [
              {label: Easy1, name: easy1, widget: image},
              {label: Easy2, name: easy2, widget: image},
              {label: Easy3, name: easy3, widget: image},
              {label: Easy4, name: easy4, widget: image},
              {label: Easy5, name: easy5, widget: image}
            ]