backend:
  name: git-gateway
  local_backend: true
  branch: master
  site_url: https://easyget.com.ua/
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "custom-pages"
    label: "Custom Pages"
    folder: "src/pages"
    filter: {field: "templateKey", value: "custom-page"}
    create: true
    slug: "{{slug}}"
    identifier_field: pather
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "custom-page"}
      - {label: "Page path", name: "pather", widget: "string"}
      - {label: "Preview", name: "preview", widget: "image", required: false}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "text", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "List", name: "textlist", widget: "list", fields: [
          {label: "Title", name: "title", widget: "string"},
          {label: "Text", name: "text", widget: "text"}
        ], required: false}
      - {label: "Products", name: "productlist", widget: "list", fields: [
          {label: "Name", name: "name", widget: "string"},
          {label: "Price", name: "price", widget: "string"},
          {label: "Link", name: "link", widget: "string"},
          {label: "Image", name: "image", widget: "image"},
        ], required: false}
      - {label: "Call to action", name: "calltoaction", widget: "object", fields: [
          {label: "Text", name: "text", widget: "string"},
          {label: "Link", name: "link", widget: "string"}
        ], required: false}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - label: EasySection
            name: easy
            widget: object
            fields: [
              {label: TitleTop, name: title_top, widget: string},
              {label: TitleBottom, name: title_bottom, widget: string},
              {label: Subtitle, name: subtitle, widget: text}
            ]
          - label: AboutSection
            name: about
            widget: object
            fields: [
              {label: Image, name: image, widget: image},
              {label: Title, name: title, widget: string},
              {label: Text, name: text, widget: text},
            ]
          - label: FreeSection
            name: free
            widget: list
            fields:
              - {label: Image, name: image, widget: image}
              - {label: Title, name: title, widget: string}
              - {label: Subtitle, name: subtitle, widget: string}
              - {label: Text, name: text, widget: text}
          - label: HowSection
            name: how
            widget: object
            fields: [
              {label: Title, name: title, widget: string},
              {label: Order Steps, name: order_steps, widget: list, fields: [
                {label: Title, name: title, widget: string},
                {label: Text, name: text, widget: text}
              ]},
              {label: Buy Steps, name: buy_steps, widget: list, fields: [
                {label: Title, name: title, widget: string},
                {label: Text, name: text, widget: text}
              ]}
            ]
          - label: OkaySection
            name: okay
            widget: object
            fields: [
              {label: Image, name: image, widget: image},
              {label: Title, name: title, widget: string},
              {label: OkayList, name: list, widget: list, fields: [{label: Text, name: text, widget: text}]}
            ]
          - label: CheapestSection
            name: cheapest
            widget: object
            fields: [
              {label: Title, name: title, widget: string},
              {label: Products, name: products, widget: list, fields: [
                {label: Name, name: name, widget: string},
                {label: Image, name: image, widget: image},
                {label: CompareList, name: compare, widget: list, fields: [
                  {label: Logo, name: logo, widget: image},
                  {label: Title, name: title, widget: string},
                  {label: Duration, name: duration, widget: string},
                  {label: Price, name: price, widget: string}
                ]}
              ]}
            ]
          - {label: ShopsSection, name: shops, widget: object, fields: [
              {label: ShopsTitle, name: title, widget: string},
              {label: ShopsSubtitle, name: subtitle, widget: text},
              {label: ShopsList, name: list, widget: list, fields: [{label: Shop, name: shop, widget: image}]}
            ]}
          - {label: FeedbackSection, name: feedbacks, widget: object, fields: [
              {label: FeedbackTitle, name: title, widget: string},
              {label: FeedbackList, name: list, widget: list, fields: [{label: Feedback, name: feedback, widget: image}]}
            ]}
          - label: LandingImages
            name: landing_images
            widget: object
            fields: [
              {label: Easy1, name: easy1, widget: image},
              {label: Easy2, name: easy2, widget: image},
              {label: Easy3, name: easy3, widget: image},
              {label: Easy4, name: easy4, widget: image},
              {label: Easy5, name: easy5, widget: image}
            ]
      - file: "src/pages/turkey.md"
        label: "Turkey Page"
        name: "turkey"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "turkey-page"}
          - label: EasySection
            name: easy
            widget: object
            fields: [
              {label: TitleTop, name: title_top, widget: string},
              {label: TitleBottom, name: title_bottom, widget: string},
              {label: Subtitle, name: subtitle, widget: text},
              {label: ButtonLink, name: link, widget: string}
            ]
          - label: ProfitSection
            name: profit
            widget: object
            fields: [
              {label: Title, name: title, widget: string},
              {label: Things, name: things, widget: list, fields: [
                {label: Title, name: title, widget: string},
                {label: Img, name: image, widget: image},
              ]}
            ]
          - label: HowSection
            name: how
            widget: object
            fields: [
              {label: Title, name: title, widget: string},
              {label: Order Steps, name: order_steps, widget: list, fields: [
                {label: Title, name: title, widget: string},
                {label: Text, name: text, widget: text}
              ]},
              {label: Buy Steps, name: buy_steps, widget: list, fields: [
                {label: Title, name: title, widget: string},
                {label: Text, name: text, widget: text}
              ]}
            ]
          - label: PopularSection
            name: popular
            widget: object
            fields: [
              {label: Title, name: title, widget: string},
              {label: Subtitle, name: subtitle, widget: string},
              {label: ShopsList, name: list, widget: list, fields: [{label: Logo, name: logo, widget: image}]}
            ]
          - label: ShopsSection
            name: shops
            widget: object
            fields: [
              {label: Title, name: title, widget: string},
              {label: Shops, name: shopslist, widget: list, fields: [
                {label: Name, name: name, widget: string},
                {label: Logo, name: logo, widget: image},
                {label: Desctription, name: description, widget: text},
                {label: Link, name: link, widget: string},
                {label: PriceList, name: prices, widget: list, fields: [{label: Type, name: type, widget: string}, {label: Prices, name: cost, widget: string}]}
              ]}
            ]
          - label: AboutSection
            name: about
            widget: object
            fields: [
              {label: Image, name: image, widget: image},
              {label: Title, name: title, widget: string},
              {label: AboutList, name: list, widget: list, fields: [{label: Title, name: title, widget: string}, {label: Text, name: text, widget: string}]}
            ]
          - label: ServiceSection
            name: service
            widget: object
            fields: [
              {label: Delivery, name: delivery, widget: object, fields: [
                {label: Title, name: title, widget: string}, 
                {label: Text, name: text, widget: text}
              ]},
              {label: Buy, name: buy, widget: object, fields: [
                {label: Title, name: title, widget: string}, 
                {label: Text, name: text, widget: text}
              ]},
              {label: ServiceList, name: servicelist, widget: list, fields: [
                {label: Title, name: title, widget: string},
                {label: Image, name: image, widget: image}
              ]}
            ]
          - label: WhySection
            name: why
            widget: object
            fields: [
              {label: Title, name: title, widgeet: string},
              {label: Text, name: text, widget: text},
              {label: Price, name: price, widget: string}
            ]
          - {label: FeedbackSection, name: feedbacks, widget: object, fields: [
              {label: FeedbackTitle, name: title, widget: string},
              {label: FeedbackList, name: list, widget: list, fields: [{label: Feedback, name: feedback, widget: image}]}
            ]}
          - label: TurkeyImages
            name: turkey_images
            widget: object
            fields: [
              {label: Turkey1, name: turkey1, widget: image},
              {label: Turkey2, name: turkey2, widget: image},
              {label: Turkey3, name: turkey3, widget: image},
              {label: Turkey4, name: turkey4, widget: image}
            ]
      - file: "src/pages/rozmytnennia-eg.md"
        label: "Розмитнення вiдправлень"
        name: "rozmytnennia-eg"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "info-page"}
          - {label: "Preview", name: "preview", widget: "image", required: false}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/rozmytnennia-np.md"
        label: "Розмитнення вiдправлень Нова Пошта"
        name: "rozmytnennia-np"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Preview", name: "preview", widget: "image", required: false}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "info-page"}
      - file: "src/pages/poryadok-utylizatsii-tovariv.md"
        label: "Порядок утилізації товарів"
        name: "poryadok-utylizatsii-tovariv"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "info-page"}
          - {label: "Preview", name: "preview", widget: "image", required: false}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/poriadok-povernennia-tovariv.md"
        label: "Порядок повернення товарів"
        name: "poriadok-povernennia-tovariv"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "info-page"}
          - {label: "Preview", name: "preview", widget: "image", required: false}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/zaboroneni-tovary.md"
        label: "Заборонені до пересилання товари"
        name: "zaboroneni-tovary"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "info-page"}
          - {label: "Preview", name: "preview", widget: "image", required: false}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/obrobka-dannih.md"
        label: "Політика конфіденційності"
        name: "obrobka-dannih"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "info-page"}
          - {label: "Preview", name: "preview", widget: "image", required: false}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/kliyentam.md"
        label: "Публічний договір"
        name: "kliyentam"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "info-page"}
          - {label: "Preview", name: "preview", widget: "image", required: false}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/mytnyi-zbir.md"
        label: "Митний збір"
        name: "mytnyi-zbir"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "info-page"}
          - {label: "Preview", name: "preview", widget: "image", required: false}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/black-friday.md"
        label: "Чорна пятниця"
        name: "black-friday"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "info-page"}
          - {label: "Preview", name: "preview", widget: "image", required: false}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
